import React, { useRef, useState } from 'react';

const MAX_CHARS = 10000;
const MIN_WORDS = 100;

function countWords(text) {
    return text.trim() === '' ? 0 : text.trim().split(/\s+/).length;
}

export default function TextInput({ onAnalyse, loading }) {
    const [text, setText] = useState('');
    const fileRef = useRef(null);

    const wordCount = countWords(text);
    const charCount = text.length;
    const isValid = wordCount >= MIN_WORDS && charCount <= MAX_CHARS;

    const wordCountColor =
        wordCount === 0 ? 'var(--text-muted)' :
            wordCount < MIN_WORDS ? 'var(--accent-amber)' :
                'var(--accent-green)';

    const handleFileChange = async (e) => {
        const file = e.target.files?.[0];
        if (!file) return;
        if (file.name.endsWith('.txt')) {
            setText((await file.text()).slice(0, MAX_CHARS));
        } else if (file.name.endsWith('.docx')) {
            try {
                const { default: mammoth } = await import('mammoth/mammoth.browser');
                const result = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() });
                setText(result.value.slice(0, MAX_CHARS));
            } catch { alert('Could not parse .docx file.'); }
        } else {
            alert('Only .txt and .docx files are supported.');
        }
        e.target.value = '';
    };

    return (
        <div className="glass-card" style={{ padding: 'clamp(14px,3vw,24px)', display: 'flex', flexDirection: 'column', gap: 'clamp(10px,2vw,16px)' }}>

            {/* Header row */}
            <div className="flex items-center justify-between gap-2 flex-wrap">
                <h2 style={{ fontSize: 'var(--text-lg)', fontWeight: 600 }}>Paste or Upload Text</h2>
                <div className="flex items-center gap-2">
                    {/* Upload */}
                    <button
                        id="upload-file-btn"
                        aria-label="Upload .txt or .docx file"
                        onClick={() => fileRef.current?.click()}
                        className="flex items-center gap-1.5 rounded-lg font-medium transition-all"
                        style={{ padding: 'clamp(6px,1.5vw,8px) clamp(10px,2vw,14px)', fontSize: 'var(--text-sm)', background: 'rgba(99,102,241,0.1)', color: 'var(--accent-blue-light)', border: '1px solid rgba(99,102,241,0.2)', minHeight: '36px' }}
                    >
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                            <polyline points="17 8 12 3 7 8" /><line x1="12" y1="3" x2="12" y2="15" />
                        </svg>
                        <span>Upload</span>
                    </button>
                    <input ref={fileRef} type="file" accept=".txt,.docx" className="hidden" onChange={handleFileChange} />

                    {/* Clear */}
                    {text.length > 0 && (
                        <button
                            id="clear-text-btn"
                            aria-label="Clear text"
                            onClick={() => setText('')}
                            className="flex items-center gap-1.5 rounded-lg font-medium transition-all"
                            style={{ padding: 'clamp(6px,1.5vw,8px) clamp(10px,2vw,14px)', fontSize: 'var(--text-sm)', background: 'rgba(239,68,68,0.08)', color: '#f87171', border: '1px solid rgba(239,68,68,0.15)', minHeight: '36px' }}
                        >
                            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
                            </svg>
                            <span>Clear</span>
                        </button>
                    )}
                </div>
            </div>

            {/* Textarea */}
            <textarea
                id="text-input-area"
                className="detect-textarea"
                placeholder="Paste text here to detect whether it was written by a human or generated by AI. Minimum 100 words required for analysis…"
                value={text}
                onChange={(e) => setText(e.target.value.slice(0, MAX_CHARS))}
                aria-label="Text input for AI detection"
            />

            {/* Footer: counters + button */}
            <div className="input-footer">
                <div className="flex items-center flex-wrap gap-x-3 gap-y-1" style={{ fontSize: 'var(--text-sm)' }}>
                    <span style={{ color: wordCountColor, fontWeight: 600 }}>
                        {wordCount}&thinsp;/&thinsp;{MIN_WORDS}+ words
                    </span>
                    {wordCount > 0 && wordCount < MIN_WORDS && (
                        <span style={{ color: 'var(--accent-amber)', fontSize: 'var(--text-xs)' }}>
                            ({MIN_WORDS - wordCount} more needed)
                        </span>
                    )}
                    <span style={{ color: 'var(--text-muted)' }}>
                        {charCount.toLocaleString()}&thinsp;/&thinsp;{MAX_CHARS.toLocaleString()} chars
                    </span>
                </div>

                <button
                    id="analyse-btn"
                    className="glow-btn analyse-btn flex items-center gap-2"
                    style={{ padding: 'clamp(10px,2vw,12px) clamp(18px,3vw,24px)', fontSize: 'var(--text-sm)' }}
                    disabled={!isValid || loading}
                    onClick={() => isValid && !loading && onAnalyse(text)}
                    aria-label="Analyse text for AI generation"
                >
                    {loading ? (
                        <>
                            <svg className="animate-spin" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
                            </svg>
                            Analysing…
                        </>
                    ) : (
                        <>
                            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <circle cx="11" cy="11" r="8" /><path d="M21 21l-4.35-4.35" />
                            </svg>
                            Analyse Text
                        </>
                    )}
                </button>
            </div>
        </div>
    );
}
